# Generated by Django 5.0.1 on 2024-04-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
