# Generated by Django 5.0.1 on 2024-04-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_stuff_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
