# Generated by Django 5.0.1 on 2024-04-13 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_alter_stuff_view_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuff',
            name='view_count',
        ),
        migrations.AddField(
            model_name='stuff',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_stuffs', to=settings.AUTH_USER_MODEL),
        ),
    ]
