# Generated by Django 5.0.1 on 2024-04-13 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_remove_stuff_view_count_stuff_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
