# Generated by Django 5.0.1 on 2024-04-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0006_remove_order_stuff_remove_order_user_stuff_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
